### ISSUE TITLE
Remove docs workflow

### ISSUE THREAD

**Issue by Tiagoquix** [mastercoms/tf2cfg#561]
Doesn't work and it is very annoying.

![image](https://user-images.githubusercontent.com/30274161/126048432-f24dffca-a375-4084-b04f-c37ef985a005.png)

**Comment by mastercoms** [comment]
Instead of fixing it?

**Comment by mastercoms** [comment]
I thought I fixed this, but turns out I never pushed the fix.

**Comment by mastercoms** [comment]
Actually, this was pushed, but never made it to the develop branch.

**Comment by Tiagoquix** [comment]
the problem persists

![image](https://user-images.githubusercontent.com/30274161/126268601-53c8ea21-46e9-4969-a185-bc840dcb2f18.png)

@mastercoms

**Comment by treacherousfiend** [comment]
This appears to actually be a different issue caused by pages not existing (and as such having dead links). Should be a simple fix?

edit: fixed as of 16344a0

**Comment by Tiagoquix** [comment]
> This appears to actually be a different issue caused by pages not existing (and as such having dead links). Should be a simple fix?
> 
> edit: fixed as of [16344a0](https://github.com/mastercomfig/mastercomfig/commit/16344a03924bf6020c130b5a12a47ca5c888cd79)

Not fixed. Although the "failed" errors did stop, the notifications did not. They are always bothering me.

@mastercoms 

![image](https://user-images.githubusercontent.com/30274161/129496595-f2617a4a-3d01-426f-bbf6-fa33124d1c12.png)

![image](https://user-images.githubusercontent.com/30274161/129496598-045e113c-a2da-44d3-ba89-e67249c8c880.png)

**Comment by mastercoms** [comment]
Try using a git client instead of repetitively editing each file separately

**Comment by treacherousfiend** [comment]
This is a different issue, looks like its due to another commit happening before the build finishes

**Comment by mastercoms** [comment]
I've attempted to disable the cancellation on PRs.

**Comment by mastercoms** [comment]
I've made an alternative solution to what cancellation was trying to solve.
