### ISSUE TITLE
Customization doesn't load

### ISSUE THREAD

**Issue by slambo311** [mastercoms/tf2cfg#623]
**Describe the bug**
On the mastercomfig website, the customization stuff just doesn't load.

**How you encountered the issue**
1. Go on the mastercomfig download page
2. Click "Customization"
3. Wait 19283413248 hours for it to not load

**Screenshots**
![image](https://user-images.githubusercontent.com/61334045/158840399-1827845d-1bc3-4412-815b-d14dc7564ddc.png)

**Desktop (please complete the following information):**
* mastercomfig version: 9.70
* Preset and addon(s): None and none.
* Custom values (if any): None for obvious reasons.
* Operating system (OS): ChromeOS (I download the stuff then send it to my actual PC via google drive, ok)
* Graphics card (GPU): I don't know where to check.
* Processor (CPU): Intel(R) Celeron(R) CPU N3060 @ 1.60GHz (2 threads, 2.48GHz)
* Memory (RAM) size in MB or GB: Don't know where to check, but considering it literally has Chrome in the name of ChromeOS, it's probably pretty low.

**Comment by slambo311** [comment]
aaand crap i should've put this on the website's repository

**Comment by mastercoms** [comment]
I can't reproduce this issue. Make sure your cache is up to date (ctrl+shift+R)

**Comment by slambo311** [comment]
Alright, ctrl shift R didn't change anything other than an "Install app" button (the app's just the same dang website but in a separate window) showing up. Still doesn't load. Maybe I'm just impatient. How long does it take for it to load for you?

**Comment by slambo311** [comment]
If it helps, Chrome says I have 3 cookies in use and the "Modules" button doesn't do anything. Plus, that update hasn't been deployed yet.

**Comment by mastercoms** [comment]
It loads in under a second for me. Could you open Dev Tools (Ctrl+Shift+I, or F12) and go to the Console tab? Let me know what messages/errors you see in there.

**Comment by slambo311** [comment]
Crap, my Chromebook doesn't let me open the dev tools.

**Comment by mastercoms** [comment]
Are you able to access https://mastercomfig.mcoms.workers.dev/?v=2

**Comment by slambo311** [comment]
Yeah. Also it doesn't load in mobile Firefox either.

**Comment by mastercoms** [comment]
Can you give me the exact URL of the page you're visiting?

**Comment by slambo311** [comment]
mastercomfig.mcoms.workers.dev/?v=2
The site just shows a bunch of HTML code, though.

**Comment by mastercoms** [comment]
I meant for the download page

**Comment by slambo311** [comment]
mastercomfig.com/app

**Comment by slambo311** [comment]
mastercomfig.com/app

**Comment by slambo311** [comment]
On the main page, it showed a windows icon on the launch button despite me being on a chromebook, if that helps.

**Comment by slambo311** [comment]
Alright, the problem still happens on my samsung phone, but that might just be because I'm using mobile data, since I'm on a bus now.
Works fine on mobile Opera GX though.

**Comment by mastercoms** [comment]
The icon is meant to be just a generic app icon, not a Windows icon. And I'm sorry, I'm out of ideas. I will try to see if I can find the issues within the next few days.

**Comment by slambo311** [comment]
Alright.

**Comment by slambo311** [comment]
Ok, so my theory is that the bug only happens on certain browsers, like Firefox and Chrome. But that's all I got.

**Comment by mastercoms** [comment]
Those are the only 2 browsers I test on

**Comment by mastercoms** [comment]
On the mastercomfig Discord, we found a possible error that prevents customizations from loading in cases where IndexedDB (a browser storage technology) is not available. I have deployed a fix which falls back to in-memory storage (which does not save anything between sessions, but at least allows the app to function). Please let me know if this resolves your issue.

**Comment by slambo311** [comment]
Alright, it still won't load. Plus, on the cookie menu thing, it still shows an indexed database. Weird.
![image](https://user-images.githubusercontent.com/61334045/159051590-500f7817-6f6e-45b1-a357-54b2620dfce5.png)

**Comment by mastercoms** [comment]
Could you force refresh the page again? I just added error tracking so maybe I will be able to see the error now. It's with sentry which may be adblocked.

**Comment by slambo311** [comment]
Alright, I force refreshed it again, still not loading. As for the sentry thing, I don't use any adblockers, plus I have the ad permission on in site settings.

**Comment by mastercoms** [comment]
I just deployed even more error tracking, since I was not able to see any errors so far. Force refresh again and I'll see if it goes through now.

**Comment by slambo311** [comment]
Alright.

**Comment by micwoj92** [comment]
@slambo311 any progress bro?

**Comment by slambo311** [comment]
> @slambo311 any progress bro?

No, not really.

**Comment by slambo311** [comment]
Alright, it's working now. At least, on Firefox it works. One really crappy extension I have (and can't delete) blocked mastercomfig on Chrome, so I can't test it on there.

**Comment by micwoj92** [comment]
> One really crappy extension I have (and can't delete) blocked mastercomfig on Chrome, so I can't test it on there.

school chromebook spyware

**Comment by slambo311** [comment]
> school chromebook spyware

Exactly.
